# Generated by Django 3.0.7 on 2020-06-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('profile_Img', models.CharField(blank=True, max_length=256)),
                ('access_Token', models.CharField(blank=True, max_length=256)),
                ('refresh_Token', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
